   name: facefusion-env
   channels:
     - defaults
     - conda-forge
   dependencies:
     - python=3.12
     - pip=25.0
     - ffmpeg=7.1.1
     - libvorbis=1.3.7
     - pip:
       - -r requirements.txt